version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    container_name: mysql
    image: mariadb:10.4.27
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: testing
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - 3307:3306
    volumes:
      - ./db-config:/var/lib/mysql

  